name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: |
          forge --version
          forge build --sizes
        id: build

      - run: |
          forge test -vv
          forge coverage --ir-minimum --report lcov
          git diff --exit-code
        id: test

  test-generate-vectors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: |
          cd test-vectors
          npm ci
          npm run generate_wycheproof
          npm test
          git diff --exit-code
        id: test

  test-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: |
          npm ci
          npm run lint && npm run build
          git diff --exit-code
        id: test
        working-directory: ./website
